[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#fff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#add8e6"

# Color used for almost all text.
textColor = "#111111"

[client]
toolbarMode = "minimal"